dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "callistom-github"
    token:
      secure: "25c43b39bb72242e77bf66219c3a590158698a7c"

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'